version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "money-distribution"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1c5jhh44rv11h"
s3_prefix = "money-distribution"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "STAGE=\"dv\" MoneyDistributionTableName=\"money-distribution\""

